export const players = [
    {
      name: "Kylian Mbappé",
      team: "Real Madrid",
      nationality: "French",
      jerseyNumber: "9",
      age: 25,
      imageUrl: "https://imgresizer.eurosport.com/unsafe/640x480/filters:format(jpeg)/origin-imgresizer.eurosport.com/2024/08/15/image-c69e92f8-acfd-4927-85c9-35cf59c1df12-72-640-480.jpeg",
      goals: 200,
      assists: 110,
      rating: 91,
    },
    {
      name: "Vinícius Júnior",
      team: "Real Madrid",
      nationality: "Brazilian",
      jerseyNumber: "7",
      age: 23,
      imageUrl: "https://i.redd.it/vbioojtj214d1.jpeg",
      goals: 50,
      assists: 40,
      rating: 89,
    },
    {
      name: "Jude Bellingham",
      team: "Real Madrid",
      nationality: "English",
      jerseyNumber: "22",
      age: 21,
      imageUrl: "https://pbs.twimg.com/media/GAc5Mc8WwAA5eyW.jpg:large",
      goals: 30,
      assists: 25,
      rating: 86,
    },
    {
      name: "Cristiano Ronaldo",
      team: "Al Nassr",
      nationality: "Portuguese",
      jerseyNumber: "7",
      age: 39,
      imageUrl: "https://media.gettyimages.com/id/624403080/photo/madrid-spain-cristiano-ronaldo-of-real-madrid-celebrate-after-scoring-reals-3rd-goal-during.jpg?s=612x612&w=gi&k=20&c=Ws2xuU-JuMj1USn0yJtAGgB_ovRbddWFzE45zTcJxb4=",
      goals: 800,
      assists: 150,
      rating: 88,
    },
    {
      name: "Sergio Ramos",
      team: "Real Madrid",
      nationality: "Spanish",
      jerseyNumber: "4",
      age: 37,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmeMmIXm1W8LT8eOzlwD_2BOLsUCuINuYLSg&s",
      goals: 130,
      assists: 40,
      rating: 87,
    },
    {
      name: "Toni Kroos",
      team: "Real Madrid",
      nationality: "German",
      jerseyNumber: "8",
      age: 34,
      imageUrl: "https://cloudfront-us-east-2.images.arcpublishing.com/reuters/DFLN2DAEVRPGHI5H7YHPUUXUIU.jpg",
      goals: 80,
      assists: 130,
      rating: 88,
    },
    {
      name: "Luka Modrić",
      team: "Real Madrid",
      nationality: "Croatian",
      jerseyNumber: "10",
      age: 38,
      imageUrl: "https://res.cloudinary.com/bleacherreport/image/upload/c_fill,h_725,w_900/otpblwcevq10wviftmpy.jpg",
      goals: 40,
      assists: 60,
      rating: 87,
    },
    {
      name: "Karim Benzema",
      team: "Al-Ittihad",
      nationality: "French",
      jerseyNumber: "9",
      age: 36,
      imageUrl: "https://cdn.vox-cdn.com/thumbor/5ACTYZuWAq9jossDhIe5dc9RHHI=/0x0:5165x3443/1200x800/filters:focal(2170x1309:2996x2135)/cdn.vox-cdn.com/uploads/chorus_image/image/73473706/1420531788.0.jpg",
      goals: 500,
      assists: 150,
      rating: 89,
    },
  ];
  